[package]
name = "dotty"
version = "0.1.0"
authors = ["Linden Krouse <ztaticnull@gmail.com>"]

[dependencies]
clap = {version = "*", features = ["yaml"] }
serde =         "*"
serde_macros =  "*"
serde_yaml =    "*"

# Deps for unit testing
scopeguard =    "*"
assert_cli =    "*"
indoc =         "*"